## Curso: Análise e Desenvolvimento de Sistemas

## Disciplina:  DISRUPTIVE ARCHITECTURES: IOT, IA & GENERATIVE AI

## Turmas: 2TDS (1o semestre de 2026)

## Professor: André Tritiack

----------------------

## **Diagnóstico médico: Problemas Ortopédicos na Coluna Vertebral**

Esse dataset contém dados sobre problemas ortopédicos na coluna vertebral, diagnosticados no Centre Médico-Chirurgical de Réadaptation des Massues, em Lyon, France. Contém 6 atributos biomecânicos para 310 entradas anonimizadas, sendo 100 de pacientes considerados sem problemas (Normal - NO), 60 de pacientes com Hérnia de Disco (Disk Hernia - DH) e 150 de pacientes com Espondilolistese (Spondylolisthesis - SL).

Maiores informações disponíveis em https://www.openml.org/d/1523

Escolha dois algoritmos para treinar seus modelos de classificação.

Opções: KNN, Random Forest, Decision Tree, Logistic Regression, SVM

In [33]:
# Criação do dataframe
import pandas as pd
from sklearn.datasets import fetch_openml

print("Baixando dados...")
dataset = fetch_openml(data_id=1523, as_frame=True, parser='auto')

df = dataset.frame

df.rename(columns={
    'V1': 'pelvic_incidence',
    'V2': 'pelvic_tilt',
    'V3': 'lumbar_lordosis_angle',
    'V4': 'sacral_slope',
    'V5': 'pelvic_radius',
    'V6': 'degree_spondylolisthesis',
    'Class': 'diagnostic'
}, inplace=True)

print("Dataframe criado!")

Baixando dados...
Dataframe criado!

In [5]:
# Visualize o tamanho do dataframe
print("Tamanho do DataFrame (linhas, colunas):", df.shape)

Tamanho do DataFrame (linhas, colunas): (310, 7)

In [6]:
# Visualize os primeiros registros
display(df.head())

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis,diagnostic
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400,1
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259,1
2,68.832021,22.218482,50.092194,46.613539,105.985136,-3.530317,1
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523,1
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501,1

In [13]:
# Mostre uma tabela com as informações dos atributos (formato dos dados)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 310 entries, 0 to 309
Data columns (total 7 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   pelvic_incidence          310 non-null    float64
 1   pelvic_tilt               310 non-null    float64
 2   lumbar_lordosis_angle     310 non-null    float64
 3   sacral_slope              310 non-null    float64
 4   pelvic_radius             310 non-null    float64
 5   degree_spondylolisthesis  310 non-null    float64
 6   diagnostic                0 non-null      float64
dtypes: float64(7)
memory usage: 17.1 KB

In [7]:
# Mostre uma tabela com as estatísticas descritivas dos atributos
display(df.describe())

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis
count,310.000000,310.000000,310.000000,310.000000,310.000000,310.000000
mean,60.496653,17.542822,51.930930,42.953831,117.920655,26.296694
std,17.236520,10.008330,18.554064,13.423102,13.317377,37.559027
min,26.147921,-6.554948,14.000000,13.366931,70.082575,-11.058179
25%,46.430294,10.667069,37.000000,33.347122,110.709196,1.603727
50%,58.691038,16.357689,49.562398,42.404912,118.268178,11.767933
75%,72.877696,22.120395,63.000000,52.695889,125.467675,41.287352
max,129.834041,49.431864,125.742386,121.429566,163.071041,418.543082

In [26]:
# Conversão de dados categóricos em numéricos (coluna "diagnostic")
mapa_diagnostico = {
    '1': 0,
    '2': 1,
    '3': 2
}
df['diagnostic'] = df['diagnostic'].map(mapa_diagnostico)

In [27]:
# Visualização dos dados da coluna "diagnostic" após a transformação
print(df['diagnostic'].value_counts())

diagnostic
2    150
1    100
0     60
Name: count, dtype: int64

Crie as variáveis X e y.

X deve ser um dataframe que contenha os dados dos seis atributos referentes aos biomarcadores (V1 a V6).

y deve ser um array com os dados da coluna "diagnostic".

In [28]:
# Coloque aqui o seu código para a variável X
X = df.drop(columns=['diagnostic'])

In [29]:
# Coloque aqui o seu código para a variável y
y = df['diagnostic'].values

In [30]:
# Visualize os primeiros registros do dataframe X
display(X.head())

,pelvic_incidence,pelvic_tilt,lumbar_lordosis_angle,sacral_slope,pelvic_radius,degree_spondylolisthesis
0,63.027818,22.552586,39.609117,40.475232,98.672917,-0.254400
1,39.056951,10.060991,25.015378,28.995960,114.405425,4.564259
2,68.832021,22.218482,50.092194,46.613539,105.985136,-3.530317
3,69.297008,24.652878,44.311238,44.644130,101.868495,11.211523
4,49.712859,9.652075,28.317406,40.060784,108.168725,7.918501

In [31]:
# Visualize X como um array Numpy (values)
X.values

array([[ 63.027818,  22.552586,  39.609117,  40.475232,  98.672917,
         -0.2544  ],
       [ 39.056951,  10.060991,  25.015378,  28.99596 , 114.405425,
          4.564259],
       [ 68.832021,  22.218482,  50.092194,  46.613539, 105.985136,
         -3.530317],
       ...,
       [ 61.446597,  22.694968,  46.170347,  38.751628, 125.670725,
         -2.70788 ],
       [ 45.252792,   8.693157,  41.583126,  36.559635, 118.545842,
          0.21475 ],
       [ 33.841641,   5.073991,  36.641233,  28.767649, 123.945244,
         -0.199249]])

In [32]:
# Visualize y como um array Numpy
print(y)

[0, 0, 0, 0, 0, ..., 1, 1, 1, 1, 1]
Length: 310
Categories (3, int64): [0, 1, 2]

Abaixo, separe 70% dos dados para treinamento e 30% para teste.

Utilize os nomes X_train, X_test, y_train e y_test

In [34]:
# Separação de dados de treinamento e teste

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

In [35]:
# Crie a instância do primeiro modelo:
modelo_rf = RandomForestClassifier(random_state=42, class_weight='balanced')

In [36]:
# Treine o primeiro modelo:
modelo_rf.fit(X_train, y_train)

RandomForestClassifier(class_weight='balanced', random_state=42)

In [37]:
# Gere o array de previsões "y_predict_1":
y_predict_1 = modelo_rf.predict(X_test)

In [39]:
# Visualize y_predict_1:
print(y_predict_1)

[1 1 1 1 0 2 2 1 1 1 1 0 2 0 1 2 1 0 2 0 2 1 2 1 2 2 1 2 2 2 0 0 1 2 1 1 2
 2 2 2 1 2 1 2 2 1 2 1 0 0 1 2 2 1 1 0 2 0 2 2 1 2 2 2 2 0 2 2 2 0 0 2 1 2
 1 0 2 1 2 2 2 2 1 2 0 2 0 1 1 2 2 2 0]

In [38]:
# Crie a instância do segundo modelo:

modelo_dt = DecisionTreeClassifier(random_state=42, class_weight='balanced')

In [40]:
# Treine o segundo modelo:
modelo_dt.fit(X_train, y_train)

DecisionTreeClassifier(class_weight='balanced', random_state=42)

In [41]:
# Gere o array de previsões "y_predict_2":
y_predict_2 = modelo_dt.predict(X_test)

In [42]:
# Visualize y_predict_2:
print(y_predict_2)

[1 2 1 1 0 1 2 1 1 1 0 0 2 0 0 2 1 1 2 0 2 1 2 1 2 2 1 2 2 2 0 0 1 2 0 1 2
 2 2 2 1 2 1 2 2 2 1 1 1 0 0 2 2 1 1 0 2 0 1 2 1 2 2 2 2 0 2 2 2 1 0 2 1 2
 1 0 2 0 2 2 2 2 2 2 0 2 0 0 1 2 2 2 0]

In [44]:
# Apresente a acurácia do primeiro modelo.
acc_rf = accuracy_score(y_test, y_predict_1)
print(f"Acurácia do primeiro modelo (Random Forest): {acc_rf * 100:.2f}%")

Acurácia do primeiro modelo (Random Forest): 80.65%

In [45]:
# Apresente a acurácia do segundo modelo.
acc_dt = accuracy_score(y_test, y_predict_2)
print(f"Acurácia do segundo modelo (Decision Tree): {acc_dt * 100:.2f}%")

Acurácia do segundo modelo (Decision Tree): 68.82%

## **Diagnóstico médico: Diabetes no povo Pima**

## Você pode construir um modelo de aprendizado de máquina para prever com precisão se os pacientes no conjunto de dados têm diabetes ou não?

Esse dataset contém dados sobre incidência de diabetes em mulheres do Povo Pima (índios nativos norte americanos originários do atual Estado do Arizona). Contém 8 atributos biomédicos para 768 entradas anonimizadas, sendo 500 testados negativo para diabetes e 268 testados positivo para diabetes.

Faça o download do dataset:

https://www.kaggle.com/datasets/uciml/pima-indians-diabetes-database


Utilize as técnicas e a mesma sequência e estrutura da primeira parte para desenvolver sua solução.

Escolha o algoritmo de sua preferência.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
#Criação e Exploração do DataFrame
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

df = pd.read_csv('/content/drive/MyDrive/FIAP/diabetes.csv')

print("Tamanho do DataFrame (linhas, colunas):", df.shape)

print("\nPrimeiros registros:")
display(df.head())

print("\nInformações dos atributos:")
df.info()

print("\nEstatísticas descritivas:")
display(df.describe())

print("\nContagem das classes na coluna 'Outcome':")
print(df['Outcome'].value_counts())

Tamanho do DataFrame (linhas, colunas): (768, 9)

Primeiros registros:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

Informações dos atributos:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

Estatísticas descritivas:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

Contagem das classes na coluna 'Outcome':
Outcome
0    500
1    268
Name: count, dtype: int64

In [9]:
#Criação das variáveis X e y
X = df.drop(columns=['Outcome'])
y = df['Outcome'].values

print("Primeiros registros de X:")
display(X.head())

print("\nVisualizando X como array Numpy (primeira linha):")
print(X.values[0])

print("\nVisualizando y como array Numpy (primeiros 15 registros):")
print(y[:15])

Primeiros registros de X:

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

Visualizando X como array Numpy (primeira linha):
[  6.    148.     72.     35.      0.     33.6     0.627  50.   ]

Visualizando y como array Numpy (primeiros 15 registros):
[1 0 1 0 1 0 1 0 1 1 0 1 0 1 1]

In [10]:
#Treinamento e Teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.30, random_state=42, stratify=y
)

modelo_rf = RandomForestClassifier(random_state=42, class_weight='balanced')

modelo_rf.fit(X_train, y_train)

y_predict = modelo_rf.predict(X_test)

print("Previsões (y_predict):")
print(y_predict[:30])

acc_rf = accuracy_score(y_test, y_predict)
print(f"\nAcurácia do modelo (Random Forest): {acc_rf * 100:.2f}%")

Previsões (y_predict):
[0 0 1 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 1 0 0 0 0 0]

Acurácia do modelo (Random Forest): 74.89%

## **Exportação do Arquivo**

In [11]:
import pickle

# Defina o caminho para salvar no seu Drive
caminho_modelo = '/content/drive/MyDrive/FIAP/modelo.pkl'

with open(caminho_modelo, 'wb') as f:
    pickle.dump(modelo_rf, f)

print("Modelo exportado como .pkl com sucesso!")

Modelo exportado como .pkl com sucesso!